### ISSUE TITLE
mistakes on non-Malay Bumiputera data

### ISSUE THREAD

**Issue by Zh9567** [TindakMalaysia/GE15-Dataset#1]
Hi, I found out that the parliament and dun composition have mistakes on non-Malay Bumiputera. The first column (labeled as Orang Asli) should be Bumiputera Sabah, the second column (labeled as Bumiputera Sabah) should be Bumiputera Sarawak, and the third column (labeled as Bumiputera Sarawak) should be Orang Asli. Could you please check it and correct them? Thanks.

**Comment by daneshchacko** [comment]
Thanks for alerting me. Will check tonight

**Comment by daneshchacko** [comment]
We established where the mistake stemmed from and made corrections of Parliamentary seats. Next in the list is to fix DUN composition

**Comment by daneshchacko** [comment]
The issue has been rectified few weeks ago
